[config]
schemaVersion = "0.0.1"


[package]
namespace = "zannc"
name = "Generalist"
versionNumber = "1.0.4"
description = "Increase pom levels! Increase max grasp! Pick your starting reward and Other Random Changes, completely configurable through ImGUI. Check README for more info!"
websiteUrl = "https://github.com/zanncdwbl/zannc-Generalist"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.44"
SGG_Modding-ModUtil = "4.0.0"
SGG_Modding-ENVY = "1.1.0"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.2"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"

[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
